fullTest:
  device:
    - model: MediumPhone.arm
      version: 34
    - model: Pixel2.arm
      version: 33
    - model: Pixel2.arm
      version: 29
smokeTest:
  device:
    - model: MediumPhone.arm
      version: 34
    - model: Pixel2.arm
      version: 30
