[versions]
agp = "8.5.1"
proton-common = "0.11.4"

# ComposeUiConvention
compose-compiler = "1.5.14"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
proton-common-mail = { module = "me.proton.mail.common:lib", version.ref = "proton-common" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
